# Generated by Django 6.0.2 on 2026-03-16 08:36

import django.core.validators
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=5)),
                ("subject", models.CharField(default="Dummy Subjects", max_length=100)),
                ("message", models.CharField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("P", "Prefer not to say"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "sender",
                    models.EmailField(
                        default="tenzin@test.com",
                        help_text="Enter your email",
                        max_length=254,
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        help_text="Enter your 10 digit mobile number",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(regex="^\\d{10}$")
                        ],
                    ),
                ),
                (
                    "pin",
                    models.PositiveIntegerField(
                        help_text="Enter 6 digit pin code",
                        validators=[pages.models.validate_pin_length],
                    ),
                ),
                ("profile_img", models.ImageField(blank=True, upload_to="profile_img")),
                ("my_file", models.FileField(blank=True, upload_to="doc")),
            ],
        ),
    ]
