# Generated by Django 6.0.2 on 2026-03-18 16:48

import django.core.validators
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=5)),
                (
                    "firstname",
                    models.CharField(help_text="Enter your first name", max_length=10),
                ),
                (
                    "lastname",
                    models.CharField(help_text="Enter your last name", max_length=10),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("P", "Prefer not to say"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="tenzin@test.com",
                        help_text="Enter your email",
                        max_length=254,
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        help_text="Enter your 10 digit mobile number",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(regex="^\\d{10}$")
                        ],
                    ),
                ),
                ("subject", models.CharField(default="Dummy Subjects", max_length=100)),
                ("message", models.CharField()),
                (
                    "pin",
                    models.PositiveIntegerField(
                        help_text="Enter 6 digit pin code",
                        validators=[pages.models.validate_pin_length],
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
