# Generated by Django 6.0.2 on 2026-03-18 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_contact_delete_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("-created_on",)},
        ),
        migrations.AddField(
            model_name="contact",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contact",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
