# Generated by Django 6.0.2 on 2026-04-03 12:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_contact_email_alter_contact_gender_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created On"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                help_text="Enter your email",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="firstname",
            field=models.CharField(
                help_text="Enter your first name",
                max_length=10,
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("P", "Prefer not to say"),
                ],
                default="M",
                help_text="Select your gender",
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="lastname",
            field=models.CharField(
                help_text="Enter your last name",
                max_length=10,
                verbose_name="Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.CharField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="mobile",
            field=models.CharField(
                help_text="Enter your 10 digit mobile number",
                max_length=10,
                unique=True,
                validators=[django.core.validators.RegexValidator(regex="^\\d{10}$")],
                verbose_name="Mobile",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="modified_on",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated On"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="pin",
            field=models.PositiveIntegerField(
                help_text="Enter 6 digit pin code",
                validators=[pages.models.validate_pin_length],
                verbose_name="Postal Code",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(
                default="Dummy Subjects", max_length=100, verbose_name="Subject"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="title",
            field=models.CharField(
                choices=[
                    ("mr", "Mr."),
                    ("mrs", "Mrs."),
                    ("ms", "Ms."),
                    ("miss", "Miss"),
                    ("dr", "Dr."),
                ],
                max_length=5,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created On"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="modified_on",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated On"),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created On"
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Updated On"),
                ),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created On"
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Updated On"),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("mr", "Mr."),
                            ("mrs", "Mrs."),
                            ("ms", "Ms."),
                            ("miss", "Miss"),
                            ("dr", "Dr."),
                        ],
                        max_length=5,
                    ),
                ),
                ("message", models.CharField()),
                ("image", models.FileField(blank=True, upload_to="images")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.review"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
            },
        ),
    ]
