# Generated by Django 6.0.2 on 2026-04-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_blog_url_alter_review_user_domain_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="review",
        ),
        migrations.AddField(
            model_name="review",
            name="blog",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="pages.blog"
            ),
        ),
    ]
