# Generated by Django 6.0.2 on 2026-04-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_remove_blog_review_review_blog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="blog",
        ),
        migrations.AddField(
            model_name="blog",
            name="reviews",
            field=models.ManyToManyField(related_name="blogs", to="pages.review"),
        ),
    ]
