# Generated by Django 6.0.2 on 2026-04-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_remove_review_blog_blog_reviews"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="message",
            new_name="description",
        ),
        migrations.AddField(
            model_name="domain",
            name="icon",
            field=models.CharField(default="bi bi-images"),
        ),
        migrations.AddField(
            model_name="domain",
            name="name",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="rated",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name",
            field=models.CharField(null=True),
        ),
    ]
